# Generated by Django 2.2.3 on 2020-06-28 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=250, verbose_name='OpenId')),
                ('union_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='UnionID')),
                ('nick_name', models.CharField(max_length=50, verbose_name='NickName')),
                ('avatar_url', models.URLField(max_length=300, verbose_name='AvatarUrl')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('gender', models.IntegerField(choices=[(1, 'man'), (2, 'woman')], verbose_name='Gender')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('user_address', models.TextField(blank=True, null=True, verbose_name='UserAddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='we_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
