# Generated by Django 2.2.3 on 2020-06-28 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManageMent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpackage',
            old_name='procuct_sku',
            new_name='product_sku',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一编码', primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='out_trade_no',
            field=models.CharField(help_text='外部支付单号（如微信平台商户订单号）', max_length=50, verbose_name='OutTradeNo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待确认'), (3, '退货中'), (4, '退款中'), (5, '已完成')], default=0, help_text='订单状态[0:待付款,1:待发货,2:待确认,3:退货中,4:退款中,5:已完成]', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='orderpackage',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一编码', primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='customer_express',
            field=models.TextField(blank=True, help_text='客户寄出的快递单号', null=True, verbose_name='CustomerExpress'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一编码', primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='out_refund_no',
            field=models.CharField(blank=True, help_text='退款单号', max_length=50, null=True, verbose_name='OutRefundNo'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.IntegerField(choices=[(0, '仅退款'), (1, '退货退款')], default=0, help_text='退回类型[0:仅退款,1:退货退款]', verbose_name='RefundType'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='state',
            field=models.IntegerField(choices=[(0, '待通过'), (1, '待退货'), (2, '待确认'), (3, '已完成'), (4, '未通过')], default=0, help_text='状态[0:待通过,1:待退货,2:待确认,3:已完成,4:未通过]', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='refundpackage',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='唯一编码', primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
