# Generated by Django 2.2.3 on 2020-05-25 21:22

import Product.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='string(150),类别名称,unique', max_length=50, unique=True, verbose_name='Name')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Category', verbose_name='Father')),
            ],
            options={
                'verbose_name': 'ProductCategory',
                'verbose_name_plural': 'ProductCategorys',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='string(150),商品唯一编码', verbose_name='Code')),
                ('id', models.CharField(auto_created=True, default=Product.models.ser_id, editable=False, help_text='string(50),流水编码', max_length=50, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(help_text='string(150),商品名称', max_length=150, verbose_name='Name')),
                ('main_image', models.ImageField(blank=True, help_text='file,主图', null=True, upload_to=Product.models.user_directory_path, verbose_name='MainImage')),
                ('image1', models.ImageField(blank=True, help_text='file,图1', null=True, upload_to=Product.models.user_directory_path, verbose_name='Image1')),
                ('image2', models.ImageField(blank=True, help_text='file,图2', null=True, upload_to=Product.models.user_directory_path, verbose_name='Image2')),
                ('image3', models.ImageField(blank=True, help_text='file,图3', null=True, upload_to=Product.models.user_directory_path, verbose_name='Image3')),
                ('image4', models.ImageField(blank=True, help_text='file,图4', null=True, upload_to=Product.models.user_directory_path, verbose_name='Image4')),
                ('image5', models.ImageField(blank=True, help_text='file,图5', null=True, upload_to=Product.models.user_directory_path, verbose_name='Image5')),
                ('description', models.TextField(blank=True, help_text='text,详情描述', null=True, verbose_name='Description')),
                ('discount', models.FloatField(blank=True, help_text='float,折扣', null=True, verbose_name='Discount')),
                ('on_sale', models.BooleanField(default=True, help_text='bool,是否在售', verbose_name='OnSale')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='datetime,创建时间', verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='datetime,更新时间', verbose_name='UpdateTime')),
                ('is_history', models.BooleanField(default=False, help_text='bool,是否历史', verbose_name='IsHistory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Product.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='SkuKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='string(50),属性名', max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'SkuKey',
                'verbose_name_plural': 'SkuKeys',
            },
        ),
        migrations.CreateModel(
            name='SkuValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='string(50),属性值名称', max_length=50, verbose_name='Name')),
                ('sku_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_info', to='Product.SkuKey', verbose_name='SkuKey')),
            ],
            options={
                'verbose_name': 'SkuValue',
                'verbose_name_plural': 'SkuValue',
            },
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='int,商品库存', verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sku', to='Product.Product', verbose_name='Product')),
                ('sku_value', models.ManyToManyField(related_name='product_sku', to='Product.SkuValue', verbose_name='SkuValue')),
            ],
            options={
                'verbose_name': 'ProductSku',
                'verbose_name_plural': 'ProductSkus',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='sku_key',
            field=models.ManyToManyField(related_name='category', to='Product.SkuKey', verbose_name='SkuKey'),
        ),
    ]
