# Generated by Django 2.2.3 on 2020-05-08 14:09

import Product.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='string(150),类别名称,unique', max_length=50, unique=True, verbose_name='Name')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Category', verbose_name='Father')),
            ],
            options={
                'verbose_name': 'ProductCategory',
                'verbose_name_plural': 'ProductCategorys',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='string(150),商品唯一编码', verbose_name='Code')),
                ('name', models.CharField(help_text='string(150),商品名称', max_length=150, verbose_name='Name')),
                ('main_image', models.ImageField(upload_to=Product.models.user_directory_path, verbose_name='MainImage')),
                ('image1', models.ImageField(upload_to=Product.models.user_directory_path, verbose_name='Image1')),
                ('image2', models.ImageField(upload_to=Product.models.user_directory_path, verbose_name='Image2')),
                ('image3', models.ImageField(upload_to=Product.models.user_directory_path, verbose_name='Image3')),
                ('image4', models.ImageField(upload_to=Product.models.user_directory_path, verbose_name='Image4')),
                ('image5', models.ImageField(upload_to=Product.models.user_directory_path, verbose_name='Image5')),
                ('description', models.TextField(blank=True, help_text='text,详情描述', null=True, verbose_name='Description')),
                ('stock', models.IntegerField(default=0, help_text='int,商品库存', verbose_name='Stock')),
                ('discount', models.FloatField(blank=True, help_text='float,折扣', null=True, verbose_name='Discount')),
                ('on_sale', models.BooleanField(default=True, help_text='bool,是否在售', verbose_name='OnSale')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='datetime,创建时间', verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='datetime,更新时间', verbose_name='UpdateTime')),
                ('is_history', models.BooleanField(default=False, help_text='bool,是否历史', verbose_name='IsHistory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Product.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='string(50),属性名', max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Spec',
                'verbose_name_plural': 'Specs',
            },
        ),
        migrations.CreateModel(
            name='SpecInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='string(50),属性值名称', max_length=50, verbose_name='Name')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_info', to='Product.Spec', verbose_name='Spec')),
            ],
            options={
                'verbose_name': 'SpecInfo',
                'verbose_name_plural': 'SpecInfos',
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_spec', to='Product.Product', verbose_name='Product')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_spec', to='Product.Spec', verbose_name='Spec')),
                ('speninfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_spec', to='Product.SpecInfo', verbose_name='SpecInfo')),
            ],
            options={
                'verbose_name': 'ProductSpec',
                'verbose_name_plural': 'ProductSpecs',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='spec',
            field=models.ManyToManyField(to='Product.Spec', verbose_name='Spec'),
        ),
    ]
