# Generated by Django 2.2.3 on 2020-05-18 21:08

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='input_type',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'checkbox'), (2, 'radio')], default=0, verbose_name='InputType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, help_text='file,图1', null=True, upload_to=Product.models.user_directory_path, verbose_name='Image1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, help_text='file,图2', null=True, upload_to=Product.models.user_directory_path, verbose_name='Image2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, help_text='file,图3', null=True, upload_to=Product.models.user_directory_path, verbose_name='Image3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, help_text='file,图4', null=True, upload_to=Product.models.user_directory_path, verbose_name='Image4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, help_text='file,图5', null=True, upload_to=Product.models.user_directory_path, verbose_name='Image5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='file,主图', null=True, upload_to=Product.models.user_directory_path, verbose_name='MainImage'),
        ),
    ]
