# Generated by Django 2.2.3 on 2020-06-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20200525_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, help_text='int,价格（单位：分）'),
        ),
        migrations.AlterField(
            model_name='speccontent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_content', to='Product.Product', verbose_name='Product'),
        ),
    ]
