# Generated by Django 2.2.3 on 2020-05-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20200518_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
