# Generated by Django 2.2.3 on 2020-05-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20200520_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspec',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='productspec',
            name='speninfo',
        ),
        migrations.AddField(
            model_name='productspec',
            name='speninfo',
            field=models.ManyToManyField(to='Product.SpecInfo', verbose_name='SpecInfo'),
        ),
    ]
