# Generated by Django 2.2.3 on 2020-05-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20200520_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspec',
            name='quantity',
            field=models.IntegerField(default=0, help_text='int,商品库存', verbose_name='Quantity'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
