# Generated by Django 2.2.3 on 2020-06-28 14:54

import Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'A user with that phone_number already exists.'}, help_text='11 characters, only numbers', max_length=18, null=True, unique=True, validators=[Base.models.PhoneNumberValidator], verbose_name='phone_number'),
        ),
    ]
